name: Java CI with Maven

on:
  push:
    tags:
      - "*"    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Maven Central Repository
      uses: actions/setup-java@v3
      with:
        java-version: 17
        server-id: ossrh
        server-username: ossrh    # Sonatype recommends using 'ossrh' as the username when using a token
        server-password: ${{ secrets.OSSRH_TOKEN }}  # Use OSSRH token for authentication
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

    - name: Debug Maven Settings
      run: |
        echo "Effective settings.xml:"
        cat ~/.m2/settings.xml || echo "(none)"
        echo "---"
        echo "GPG version:"
        gpg --version

    - name: Deploy with Maven
      run: mvn -B clean deploy -Pci-cd
      env:
        OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}  # Token for authentication with Sonatype
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}  # GPG passphrase for signing
